// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnrSOM-qSw4l-A28idZMF4WOF4NdXU8kk',
    appId: '1:1061373496172:web:0ea5c165e335e0967cc149',
    messagingSenderId: '1061373496172',
    projectId: 'keep-notes-auth',
    authDomain: 'keep-notes-auth.firebaseapp.com',
    storageBucket: 'keep-notes-auth.firebasestorage.app',
    measurementId: 'G-3ZB391EZLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP5O7EjZrrkKtVhLOxae_yTkOYFEdi9tI',
    appId: '1:1061373496172:android:f48ad0536bc7d5e77cc149',
    messagingSenderId: '1061373496172',
    projectId: 'keep-notes-auth',
    storageBucket: 'keep-notes-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDwIjP0P3KxmfMKZ0cofs90zh0DxN-k30',
    appId: '1:1061373496172:ios:87131fdc44eebf997cc149',
    messagingSenderId: '1061373496172',
    projectId: 'keep-notes-auth',
    storageBucket: 'keep-notes-auth.firebasestorage.app',
    iosClientId: '1061373496172-hok2205bq88s07qn5s5rsv61j7u7val7.apps.googleusercontent.com',
    iosBundleId: 'com.example.keepNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDwIjP0P3KxmfMKZ0cofs90zh0DxN-k30',
    appId: '1:1061373496172:ios:87131fdc44eebf997cc149',
    messagingSenderId: '1061373496172',
    projectId: 'keep-notes-auth',
    storageBucket: 'keep-notes-auth.firebasestorage.app',
    iosClientId: '1061373496172-hok2205bq88s07qn5s5rsv61j7u7val7.apps.googleusercontent.com',
    iosBundleId: 'com.example.keepNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnrSOM-qSw4l-A28idZMF4WOF4NdXU8kk',
    appId: '1:1061373496172:web:41f6c5b3180ad5217cc149',
    messagingSenderId: '1061373496172',
    projectId: 'keep-notes-auth',
    authDomain: 'keep-notes-auth.firebaseapp.com',
    storageBucket: 'keep-notes-auth.firebasestorage.app',
    measurementId: 'G-8R477ME1BE',
  );

}